### ISSUE TITLE
Changing the about repository's website

### ISSUE THREAD

**Issue by wkm97** [linkedin-faq/md2practice#1]
Hi @Ebazhanov , I have transfer the repo here. Seems like I can't edit the about repo here. If you are able to edit it, can you change it from to wkm97.github.io/md2practice/ to https://linkedin-faq.github.io/md2practice/

**Comment by Ebazhanov** [comment]
sure, done! 
but sounds like you do not have access to you own repo, after transferred it right?

**Comment by wkm97** [comment]
Not sure about it haha, I think to transfer I need to have create permission. For this case I just couldn't find the edit button for about, maybe need to be in dev-team to have permission for it? So I guess this is considered as close? The website works fine as well.

**Comment by Ebazhanov** [comment]
wait can you please check it now, I have added you to the dev team. Ok will close the issue, thanks

**Comment by wkm97** [comment]
@Ebazhanov , still couldn't find the edit button, but I think it's okay for now.
![image](https://user-images.githubusercontent.com/31875755/148956790-438c2799-eeb2-4244-aeda-d0c25923c55e.png)
